name: Profile 3D Contrib

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install -g github-profile-3d-contrib

    - name: Git 구성
      run: |
        git config user.name "kory199"
        git config user.email "kory199@gmail.com"

    - name: 커밋 및 푸시
      run: |
        git add -A .
        git commit -m "generated"
        git push

    - name: Profile 3D Contrib 업데이트
      run: github-profile-3d-contrib --username kory199 --repository kory199
